import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import ToastNotification from "@/components/ui/ToastNotification";

const outfit = Outfit({subsets: ['latin']})


export const metadata: Metadata = {
  title: "Front Next - Red Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        {children}
        
        <ToastNotification/>
      </body>
    </html>
  );
}
